sudo: required
services:
  - docker

before_install:
  - docker build -t kevinfdtr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kevinfdtr/react-test npm test -- --coverage

after_success:
  - docker build -t kevinfdtr/multi-client ./client
  - docker build -t kevinfdtr/multi-nginx ./nginx
  - docker build -t kevinfdtr/multi-server ./server
  - docker build -t kevinfdtr/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kevinfdtr/multi-client
  - docker push kevinfdtr/multi-nginx
  - docker push kevinfdtr/multi-server
  - docker push kevinfdtr/multi-worker
  
deploy:
  provider: elasticbeanstalk
  regios: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-827324543565
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY